[robinson]
modules = [
"vebas.tracking.components.cv",
"vebas.tracking.components.control",
"vebas.tracking.components.filter",
"vebas.tracking.components.transform",
"vebas.tracking.kf_ctl_loop.components",
"robinson_flow.pyflow_nodes.Robinson.Nodes.Misc",
"robinson_flow.pyflow_nodes.Robinson.Nodes.OpenCV",
]

functions = [
"vebas.utils.latlon2tuple"
]

[environment]
    [environment.mqtt]
    server = "192.168.67.134"

[AddHello]
fstring = "Hello Config {msg}"

[AddHello1]
fstring = "Hello 1 {msg}"
