default:
  logging:
    version: 1
    root:
      handlers:
        - stream_handler
        - robinson_handler
      level: DEBUG
    handlers:
      stream_handler:
        class: logging.StreamHandler
        formatter: default
        stream: "ext://sys.stderr"
      socket_handler:
        class: logging.handlers.SocketHandler
        formatter: default
        host: '127.0.0.1'
        port: 19996
      robinson_handler:
        class: robinson.logging.RobinsonLoggingHandler
        formatter: default
        # name: robinsonlogger
        # mqtt_uri: localhost
    formatters:
      default:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%H:%M:%S.%03d"
  environment:
    dynaconf_merge: True
    connectors:
        mqtt:
            class: robinson_flow.connector.MQTTConnector
        mavlink:
            class: robinson_flow.connector.MavlinkConnector
    connections:
        "/mavlink":
            topic: "/mavlink"
            connector: mqtt
            msgtype: MAVLink_message
            transform: JsonTransform
            transform_args: MAVLink_message
        "/mavlink/(?P<name>.*)":
            topic: "/mavlink/{name}"
            connector: mqtt
            msgtype: MAVLink_message
            transform: JsonTransform
            transform_args: MAVLink_message
        uav_camera_down:
            connector: mqtt
            topic: "camera/image"
            msgtype: Image
            transform: JsonTransform
            transform_args: Image
        "(?P<name>.*image.*)":
            connector: mqtt
            topic: "{name}"
            msgtype: Image
            transform: JsonTransform
            transform_args: Image
        uav_seedling_detection_local_ned:
            connector: mqtt
            topic: "detection/ned_local"
            msgtype: dict
            transform: JsonTransform
        uav_seedling_detection_global_ned:
            connector: mqtt
            topic: "detection/ned_global"
            msgtype: dict
            transform: JsonTransform
        uav_seedling_detection_latlon:
            connector: mqtt
            topic: "detection/latlon"
            msgtype: dict
            transform: JsonTransform
        uav_seedling_detection_xy:
            connector: mqtt
            topic: "detection/xy_pixel"
            msgtype: dict
            transform: JsonTransform
        uav_seedling_detection_angle:
            connector: mqtt
            topic: "detection/xy_angle"
            msgtype: dict
            transform: JsonTransform
        tracking_image:
            connector: mqtt
            topic: "tracking/image"
            msgtype: Image
            transform: JsonTransform
            transform_args: Image
        "seedling_position/(.*)":
            connector: mqtt
            topic: "tracking/{0}"
            msgtype: dict
            transform: JsonTransform
        "vebas_seedlingslist":
            connector: mqtt
            topic: "tracking/{0}"
            msgtype: dict
            transform: JsonTransform
        "(.*)":
            connector: mqtt
            topic: "{0}"
            msgtype: dict
            transform: JsonTransform

dev-pi:
  environment:
    dynaconf_merge: True
    connectors:
      mqtt:
        server: 192.168.67.172
      mavlink:
        uri: "udpin:192.168.100:14551"

dev-local:
  environment:
    dynaconf_merge: True
    connectors:
      mqtt:
        server: 127.0.0.1
      mavlink:
        uri: "udpin:127.0.0.1:14551"

dev-xps9500:
  environment:
    dynaconf_merge: True
    connectors:
      mqtt:
        server: 192.168.67.165
      mavlink:
        uri: "udpin:192.168.67.100:14551"

dev-pre75:
  environment:
    dynaconf_merge: True
    connectors:
      mqtt:
        server: 192.168.67.134
      mavlink:
          uri: "udpin:192.168.67.100:14551"
